### ISSUE TITLE
feature request --format json 

### ISSUE THREAD

**Issue by CarlFK** [raspberrypi/libcamera-apps#216]
In case I ever need to parse the output, i'll be happy if I can pipe it into a json parser.

```
pi@rpi-x:~ $ libcamera-hello -v
Options:
    verbose: 1
    info_text:#%frame (%fps fps) exp %exp ag %ag dg %dg
    timeout: 5000
    width: 0
    height: 0
    output: 
    post_process_file: 
```

There is a lot of output going on.  I hope it is as simple as wrapping everything in []

And no I don't need this now, or maybe ever, but I do often need it and get grumpy when not having it makes stuff hard given how easy it might be to make it easy.

plan B is for python bindings and then I get data types and all that, but creating/maintaining that is probably harder.
